
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.17.4
          cache: yarn
          cache-dependency-path: |
            app/yarn.lock
            api/yarn.lock

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql user: postgres
          postgresql password: password

      - name: Lint and Test APP
        working-directory: ./app
        run: |
          yarn install
          yarn lint
          yarn test

      - name: Lint and Test API
        working-directory: ./api
        run: |
          yarn install
          yarn lint
          yarn test
